# Deployment file for SSEC GPU cluster.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: olaf
  namespace: jnoss
  labels:
    app: olaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olaf
  template:
    metadata:
      labels:
        app: olaf
    spec:
      containers:
      - name: olaf
        securityContext:
          privileged: true
        image: containers.repo.sciserver.org/jnoss/olaf:latest
        imagePullPolicy: Always
        command:
          - sleep
          - "999999999"
        resources:
          limits:
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /sciserver/vc_crypt/ssec/jnoss
          name: sciserver-mount
          readOnly: false
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-80GB
      volumes:
        - name: sciserver-mount
          nfs:
            path: /srv/vc_crypt/ssec/jnoss
            server: sciserver-fs1
